version: 0.0
os: linux
#files:
 # - source: /
  #  destination: /home/ubuntu/
hooks:
  AfterInstall:
    - location: scripts/after-install.sh
      timeout: 120
      runas: root
  ApplicationStart:
    - location: scripts/start-process.sh
      timeout: 120
      runas: root
