version: 0.0
os: linux

hooks:
  ApplicationStop:
    - location: scripts/after_install.sh
      timeout: 120
      runas: root
  ApplicationStart:
    - location: scripts/start-process.sh
      timeout: 120
      runas: root
