version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 149536475906.dkr.ecr.ap-south-1.amazonaws.com
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t testnode .
  post_build:
    commands:
      - echo Tagging the Docker image...
      - docker tag testnode:latest 149536475906.dkr.ecr.ap-south-1.amazonaws.com/testnode:latest
      - echo Pushing the Docker image to ECR...
      - docker push 149536475906.dkr.ecr.ap-south-1.amazonaws.com/testnode:latest

artifacts:
  files: imagedefinition.json
