version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 149536475906.dkr.ecr.ap-south-1.amazonaws.com
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t testnode .
      - docker tag testnode:latest 149536475906.dkr.ecr.ap-south-1.amazonaws.com/testnode:latest
      - echo Creating imagedefinitions.json...
      - echo '[{"name":"testnode","imageUri":"149536475906.dkr.ecr.ap-south-1.amazonaws.com/testnode:latest"}]' > imagedefinition.json
  post_build:
    commands:
      - echo Pushing the Docker image to ECR...
      - docker push 149536475906.dkr.ecr.ap-south-1.amazonaws.com/testnode:latest
      - echo Docker image pushed to ECR successfully!
      - echo Updating ECS service...
    

artifacts:
  files:
    - imagedefinition.json
