version: 0.2

phases:
  build:
    commands:
      - npm install  # Install dependencies
      - docker build -t 207567793991.dkr.ecr.us-east-1.amazonaws.com/myapp:latest .  # Build Docker image
      - docker push 207567793991.dkr.ecr.us-east-1.amazonaws.com/myapp:latest  # Push Docker image to ECR
