version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t your-docker-repo/node-app:latest .
      - echo Pushing the Docker image...
      - docker push your-account-id.dkr.ecr.your-region.amazonaws.com/node-app:latest
  post_build:
    commands:
      - echo Writing image definitions...
      - printf '[{"name":"node-app","imageUri":"%s"}]' your-account-id.dkr.ecr.your-region.amazonaws.com/node-app:latest > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
